langauge: node_js
node_js:
- '5'
script: bash ./run/deploy.sh
env:
  global:
  - GH_NAME: "<your name/Travis CI>"
  - GH_EMAIL: "<email>"
  - GH_REF: "github.com/<username>/<project>.git"
  - GH_BRANCH: "<gh-pages/master>"
  - secure: "<----- Your encrypted key here ----->"
notifications:
    email: false
